spring.application.name=backend
spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=none

spring.mongodb.uri=${MONGODB_URI}
app.admin.github-id=${GITHUB_ADMIN_ID}

